#!/bin/bash

echo -e "Enter commit message :"
read message

echo -e "The password is : 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"
echo
echo "Pulling the lastest changes:"
git pull

echo
echo "Adding & committing the new changes:"
git add .
git commit -m "${message}"

echo
echo "Pushing the new changes:"
git push
