#!/usr/bin/env bash
# A bash script that installs nginx on your web-01

sudo su

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo chown -R ubuntu:ubuntu /var/www/html
sudo chmod -R 755 /var/www

sudo echo "Hello World!" > /var/www/html/index.html
