#!/usr/bin/env bash
# A bash script that redirect /redirect_me to another page

file="/etc/nginx/nginx.conf"

sudo service nginx start

sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx_original_conf
sudo chown -R "$USER":"$USER" $file
sudo chmod -R 664 $file

echo -e "events {}\n" > $file
{
	echo -e "http {\n"
	echo -e "\tserver {\n"
	echo -e "\t\tlisten 80;"
	echo -e "\t\troot /var/www/html;\n"
	echo -e "\t\tlocation /redirect_me {\n"
	echo -ne "\t\t\treturn 301 "
	echo -e "https://www.youtube.com/watch?v=QH2-TGUlwu4;"
	echo -e "\t\t}"
	echo -e "\t}\n"
	echo -e "\tinclude /etc/nginx/mime.types;"
	echo -e "}"
} >> $file

sudo nginx -s reload
sudo service nginx restart
