#!/usr/bin/env bash
# A bash script that redirect /redirect_me to another page

# Define some variables
default_file="/etc/nginx/sites-available/default"
url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
line1="\terror_page 404 /custom_404.html;"
line2="\tlocation = /custom_404.html {"
line3="\t\troot /var/www/html;"
line4="\t\tinternal;"
line5="\t}"
replace1="24i\\"
replace2="25i\\"

# Updating and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start

# Adjust the firewall to open only on port 80
sudo ufw allow 'Nginx HTTP'

# Set up new document root directories
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Make a backup of index.html file
sudo cp /var/www/html/index.html /var/www/html/index.html.bckp

# Create a new static web page
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 not found page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Set up /redirect_me to a youtubr video
sudo sed -i "$replace1\trewrite ^/redirect_me $url permanent;" $default_file

# Set up 404 not found page to custom_404.html
sudo sed -i "$replace2$line1\n$line2\n$line3\n$line4\n$line5" $default_file

# Restart nginx
sudo nginx -s reload
sudo service nginx restart
