#!/usr/bin/env bash
# Installs loader balancer:
# - Configures HAproxy on your lb-01 server.
# - Sends traffic to web-01 and web-02.
# - Enables management via the init script.
# - Using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat << EOT | sudo tee -a /etc/haproxy/haproxy.cfg

frontend web

    bind *:80
    default_backend web-backend

backend web-backend

    balance roundrobin
    server web-01 107.23.108.21:80 check
    server web-02 107.23.108.21:80 check

EOT

sudo service haproxy restart
