#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# The script should only display:
# username, user id, and Home directory path for the user

list=$(< /etc/passwd cut -d ':' -f 1,3,6)
list_size=${#list[@]}
i=0

while [[ $i -lt $list_size ]]
do
    echo "${list[$i]}"

    (( i++ ))
done
